-- MySQL Script generated by MySQL Workbench
-- 12/13/14 18:18:04
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema HCRIS_db_96
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `HCRIS_db_96` ;

-- -----------------------------------------------------
-- Schema HCRIS_db_96
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `HCRIS_db_96` ;
USE `HCRIS_db_96` ;

-- -----------------------------------------------------
-- Table `HCRIS_db_96`.`RPT`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `HCRIS_db_96`.`RPT` ;

CREATE TABLE IF NOT EXISTS `HCRIS_db_96`.`RPT` (
  `RPT_RC_NUM` INT NOT NULL,
  `PRVDR_CTRL_TYPE_CD` CHAR(2) NULL,
  `PRVDR_NUM` CHAR(6) NOT NULL,
  `NPI` INT NULL,
  `RPT_STUS_CD` CHAR(1) NOT NULL,
  `FY_BGN_DT` DATE NULL,
  `FY_END_DT` DATE NULL,
  `PROC_DT` DATE NULL,
  `INITL_RPT_SW` CHAR(1) NULL,
  `LAST_RPT_SW` CHAR(1) NULL,
  `TRNSMTL_NUM` CHAR(2) NULL,
  `FI_NUM` CHAR(5) NULL,
  `ADR_VNDR_CD` CHAR(1) NULL,
  `FI_CREAT_DT` DATE NULL,
  `UTIL_CD` CHAR(1) NULL,
  `NPR_DT` DATE NULL,
  `SPEC_IND` CHAR(1) NULL,
  `FI_RCPT_DT` DATE NULL,
  PRIMARY KEY (`RPT_RC_NUM`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = big5;


-- -----------------------------------------------------
-- Table `HCRIS_db_96`.`NMRC`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `HCRIS_db_96`.`NMRC` ;

CREATE TABLE IF NOT EXISTS `HCRIS_db_96`.`NMRC` (
  `RPT_RPT_RC_NUM` INT NOT NULL,
  `WKSHT_CD` CHAR(7) NOT NULL,
  `LINE_NUM` CHAR(5) NOT NULL,
  `CLMN_NUM` CHAR(4) NOT NULL,
  `ITM_VAL_NUM` VARCHAR(45) NOT NULL,
  CONSTRAINT `fk_NMRC_RPT`
    FOREIGN KEY (`RPT_RPT_RC_NUM`)
    REFERENCES `HCRIS_db_96`.`RPT` (`RPT_RC_NUM`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HCRIS_db_96`.`ALPHA`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `HCRIS_db_96`.`ALPHA` ;

CREATE TABLE IF NOT EXISTS `HCRIS_db_96`.`ALPHA` (
  `RPT_RPT_RC_NUM` INT NOT NULL,
  `WKSHT_CD` CHAR(7) NOT NULL,
  `LINE_NUM` CHAR(5) NOT NULL,
  `CLMN_NUM` CHAR(4) NOT NULL,
  `ALPHNMRC_ITM_TXT` VARCHAR(45) NOT NULL,
  CONSTRAINT `fk_ALPHA_RPT1`
    FOREIGN KEY (`RPT_RPT_RC_NUM`)
    REFERENCES `HCRIS_db_96`.`RPT` (`RPT_RC_NUM`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HCRIS_db_96`.`ROLLUP`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `HCRIS_db_96`.`ROLLUP` ;

CREATE TABLE IF NOT EXISTS `HCRIS_db_96`.`ROLLUP` (
  `RPT_RPT_RC_NUM` INT NOT NULL,
  `LABEL` CHAR(30) NOT NULL,
  `ITEM` INT NOT NULL,
  CONSTRAINT `fk_ROLLUP_RPT1`
    FOREIGN KEY (`RPT_RPT_RC_NUM`)
    REFERENCES `HCRIS_db_96`.`RPT` (`RPT_RC_NUM`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
